# 设置端口号
server:
  port: 8081

# spring配置
spring:
  # 静态资源配置
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
    # 静态资源访问
    # static-path-pattern: /static/**
  # ThymeLeaf配置
  thymeleaf:
    # 模板的模式，支持 HTML XML TEXT JAVASCRIPT
    mode: HTML
    # 编码，可不用配置
    encoding: UTF-8
    servlet:
      # 内容类别，可不用配置
      content-type: text/html
    # 开发配置为false，避免修改模板还要重启服务器
    cache: false
    # 配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    check-template-location: true
    check-template: true
  # 上传配置
  servlet:
    multipart:
      # 上传文件总的最大值
      max-request-size: 1024MB
      # 单个文件的最大值
      max-file-size: 1024MB
      # 开启多文件长传
      enabled: true
  # SQL开发配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ted?serverTimezone=GMT&characterEncoding=utf-8&useUnicode=true
    username: demo
    password: demo
  # jackson配置
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      # 格式化输出
      indent_output: true
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    # 设置空如何序列化
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      # 允许出现特殊字符和转义符
      allow_unquoted_control_chars: true
      # 允许出现单引号
      allow_single_quotes: true
    # 时区
    time-zone: Asia/Shanghai
  # Redis配置
  redis:
    # 服务器
    host: 127.0.0.1
    # 端口
    port: 6379
    # 连接池配置
    lettuce:
      pool:
        # 连接池最大链接数默认值为8
        max-active: 8
        # 连接池最大阻塞时间（使用负值表示没有限制）默认为-1
        max-wait: -1
        # 连接池中的最大空闲连接数 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接数 默认为8
        min-idle: 8
  # 面向切面
  aop:
    auto: true
    proxy-target-class: true

# MyBatis接口文件位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ted
  # 打印SQL，方便调试
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatis分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  params: count=countSql
  support-methods-arguments: true

# 日志配置
#logging:
#  # 日志级别
#  level:
#    # 包名： 级别trace < debug < info < warn < error
#    root: info
#  file:
#    # 日志文件路径：项目工程目录下/_log
#    path: ./_log
